fix an error caused by not using the -p argument
When called with "-A <password>" instead of "-p <password>"
the following error was reported:

./check_cisco_ip_sla.py -H <IP addr> -v 3 -a SHA -A <USM auth password> -l authNoPriv -u <USM username> -m check -e 10 --perf
Traceback (most recent call last):
  File "/home/orbis/./check_cisco_ip_sla.py", line 956, in <module>
    result = checker.run()
  File "/home/orbis/./check_cisco_ip_sla.py", line 75, in run
    self.create_snmp_session()
  File "/home/orbis/./check_cisco_ip_sla.py", line 261, in create_snmp_session
    self.session = Session(
  File "/usr/lib/nagios/plugins/external/venv-check_cisco_ip_sla/lib/python3.9/site-packages/easysnmp/session.py", line 259, in __init__
    self.sess_ptr = interface.session_v3(
TypeError: argument 14 must be str, not None

Now one can use -A and/or -X without providing -p.